### ISSUE TITLE
Change SignalR Nuget package to official one 

### ISSUE THREAD

**Issue by Magik3a** [Magik3a/PatientManagement_Admin#130]
For the signalr implamentation:  Latest SignalR package was introduced with verry big article before a week check the link [HERE](https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/)

**Comment by Magik3a** [comment]
Used package is in alfa state and it depends on some others that are not fully needed for .net core 2.0  and there is some warnings about that in the build proccess

**Comment by Magik3a** [comment]
Implement reload lookup for tenants on new user registration

**Comment by Magik3a** [comment]
Limitation after update 
The WebSockets transport will not work if the server hosting SignalR is running behind IIS on Windows 7 or Windows Server 2008 R2, due to limitations in IIS

**Comment by Magik3a** [comment]
SignalR Package is trowing error that probbably bloks the IIS Application Pool. Allot of problems with recycling iis pool 
![image](https://user-images.githubusercontent.com/10474555/46673274-129b1180-cbe2-11e8-8143-7ec94e4025e8.png)

**Comment by Magik3a** [comment]
Even with the new package, SignalR is trowing exception: 
```
Application: dotnet.exe
CoreCLR Version: 4.6.26919.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException: Collection was of a fixed size.
   at System.SZArrayHelper.Remove[T](T value)
   at Microsoft.AspNetCore.SignalR.Messaging.Subscription.RemoveEvent(String key)
   at Microsoft.AspNetCore.SignalR.Messaging.DefaultSubscription.RemoveEvent(String eventKey)
   at Microsoft.AspNetCore.SignalR.Messaging.MessageBus.DisposeSubscription(Object state)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at PatientManagement.Program.Main(String[] args) in C:\projects\clario-admin\PatientManagement\PatientManagement.Web\Initialization\Program.cs:line 13
```

**Comment by Magik3a** [comment]
Signalr Error is finnaly fixed!!!
Never forget to add the check for: Remove additional files at destination

![image](https://user-images.githubusercontent.com/10474555/46755840-c679cb00-ccce-11e8-93cf-81a0e4da0091.png)
